spring:
  application:
    name: service-auth
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.250
    database: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bgcz?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework.security: debug

