version: '3'
services:
    discover-01.cheerspublishing.com: 
      image: docker-repostory.cheerspublishing.com:5000/cheers/discover:latest
      container_name: discover-01
      hostname: discover-01.cheerspublishing.com
      ports: 
        - "8788:8761"
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      environment:
        - spring.profiles.active=discover-01
    discover-02.cheerspublishing.com: 
      image: docker-repostory.cheerspublishing.com:5000/cheers/discover:latest
      container_name: discover-02
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      environment:
        - spring.profiles.active=discover-02
    config:
      image: docker-repostory.cheerspublishing.com:5000/cheers/config:latest
      container_name: config
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      environment:
        - spring.profiles.active=dev
      depends_on:
        - discover-01.cheerspublishing.com
        - discover-02.cheerspublishing.com
      restart: always
    gateway: 
      image: docker-repostory.cheerspublishing.com:5000/cheers/gateway:latest
      ports: 
        - "8789:8090"
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      depends_on:
        - discover-01.cheerspublishing.com
        - discover-02.cheerspublishing.com
      restart: always
    tm-01.cheerspublishing.com: 
      image: docker-repostory.cheerspublishing.com:5000/cheers/tm:latest
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      environment:
        - spring.profiles.active=dev
      depends_on:
        - config
      restart: always
    share: 
      image: docker-repostory.cheerspublishing.com:5000/cheers/share:latest
      extra_hosts:
        - "logstash-01.cheerspublishing.com:192.168.1.250"
      environment:
        - spring.profiles.active=dev
      depends_on:
        - config
      restart: always




