eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discover-01.cheerspublishing.com:8761/eureka/,http://discover-02.cheerspublishing.com:8762/eureka/
server:
  port: 8788
spring:
  application:
    name: service-zj
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  rabbitmq:
    host: 192.168.1.253
    username: guest
    password: guest
    port: 5672
#  zipkin:
#    base-url: http://192.168.1.253:9411/ # 指定了 Zipkin 服务器的地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
test: hehhe
